port: 8080
hostname: "localhost"
access_log_level: Disabled
secret_key_file: "secret.key"
hydra_connection_string: "postgresql://hydra@/hydra"
hercules_connection_string: "postgresql://hercules@/hercules"
data_path: "/var/lib/hercules"
